import { createI18n } from "vue-i18n";

const messages = {
  en: {
    search: "Select city...",
    january: "january",
    february: "february",
    march: "march",
    april: "april",
    may: "may",
    june: "june",
    july: "july",
    august: "august",
    september: "september",
    october: "October",
    november: "November",
    december: "December",
    monday: "monday",
    tuesday: "tuesday",
    wednesday: "wednesday",
    thursday: "thursday",
    friday: "friday",
    saturday: "saturday",
    sunday: "sunday",
    high: "high",
    low: "low",
    wind: "wind",
    humidity: "humidity",
    sunrise: "sunrise",
    sunset: "sunset",
    ms: "m/s",
    feels_like: "feels like",
    mmHg: "mm Hg",
    unknown_error: "Unknown error. Try again",
    no_results: "no results",
    too_many: "Too many requests. Try again later",
  },
  ru: {
    search: "Найти город...",
    january: "январь",
    february: "февраль",
    march: "март",
    april: "апрель",
    may: "май",
    june: "июнь",
    july: "июль",
    august: "август",
    september: "сентябрь",
    october: "октябрь",
    november: "ноябрь",
    december: "декабрь",
    monday: "понедельник",
    tuesday: "вторник",
    wednesday: "среда",
    thursday: "четверг",
    friday: "пятница",
    saturday: "суббота",
    sunday: "воскресенье",
    high: "максимальная",
    low: "минимальная",
    wind: "ветер",
    humidity: "влажность",
    sunrise: "восход",
    sunset: "закат",
    ms: "м/с",
    feels_like: "ощущается как",
    mmHg: "мм Рт",
    unknown_error: "Неизвестная ошибка. попробуйте еще раз",
    no_results: "нет результатов",
    too_many: "Слишком много попыток. Попробуйте позже",
  },
};

// Create VueI18n instance with options
export const i18n = createI18n({
  legacy: false,
  locale: "en", // set locale
  fallbackLocale: "en",
  messages, // set locale messages
});
